In [1]:
import pandas as pd # type: ignore
from sklearn.model_selection import train_test_split # type: ignore
from sklearn.preprocessing import LabelEncoder, StandardScaler # type: ignore

data = pd.read_csv('travel_data.csv')
data

,Number_of_Travelers,Budget,Area_of_Interest,Warm,Transportation_Mode,Recommendation
0,6,35000,Beach,Warm,Bikes,"Marble Beach, Trincomalee"
1,4,80000,Forest,Tropical,Public Transport,"Sinharaja Forest Reserve, Deniyaya"
2,2,70000,City,Moderate,Van,"Kurunegala City, Kurunegala"
3,6,17000,Beach,Warm,Bikes,"Jungle Beach, Unawatuna"
4,25,55000,Forest,Tropical,Public Transport,"Hiyare Reservoir, Galle"
...,...,...,...,...,...,...
5744,12,25000,Forest,Tropical,Bikes,"Hiyare Reservoir, Galle"
5745,4,48000,Desert,Hot,Rosa Bus,"Delft Island, Jaffna"
5746,1,15000,National Park,Warm,Rosa Bus,"Kaudulla National Park, Polonnaruwa"
5747,20,90000,National Park,Warm,Bikes,"Wilpattu National Park, Wilpattu"
5748,10,17000,Forest,Tropical,Van,"Hiyare Reservoir, Galle"